 version: 2
 jobs:
   build:
     docker:
       - image: abazovic/fs-vanilla
     steps:
       - checkout
       - run:
           name: Start FS and run tests on it  
           #TODO Check why fs is not starting
           command: apt-get install -y default-jdk && freeswitch -ncwait && fs_cli -x status && ./gradlew clean test --debug
           environment:
              TERM: dumb

# Output on circleci when runing: freeswitch -ncwait && fs_cli -x status
# 384 Backgrounding.
# FreeSWITCH[383] Waiting for background process pid:384 to be ready.....
# FreeSWITCH[383] Waiting for background process pid:384 to be ready.....
# FreeSWITCH[383] Waiting for background process pid:384 to be ready.....
# FreeSWITCH[383] Waiting for background process pid:384 to be ready.....
# FreeSWITCH[383] Waiting for background process pid:384 to be ready.....
# FreeSWITCH[383] Waiting for background process pid:384 to be ready.....
# FreeSWITCH[383] Waiting for background process pid:384 to be ready.....
# FreeSWITCH[383] System Ready pid:384
# [ERROR] fs_cli.c:1679 main() Error Connecting []
# Exited with code 255