 version: 2
 jobs:
   build:
     docker:
       - image: abazovic/fs-vanilla
     steps:
       - checkout
       - run:
           name: Build and run Docker image
           command: apt-get install -y default-jdk && freeswitch -ncwait && ./gradlew clean test
           environment:
              TERM: dumb