 version: 2
 jobs:
   build:
     docker:
       - image: abazovic/fs-vanilla
     steps:
       - checkout
       - run:
           name: Start FS and run tests on it  
           command: apt-get install -y default-jdk && freeswitch -ncwait && fs_cli -x status && ./gradlew clean test --debug
           environment:
              TERM: dumb